<?php

/**
 * Subscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Bal_Model_Subscriber extends Base_Subscriber
{

	/**
	 * Apply modifiers
	 * @return
	 */
	public function setUp ( ) {
		$this->hasMutator('tagstr', 'setTagstr');
		$this->hasAccessor('tagarray', 'getTagArray');
		parent::setUp();
	}
	
	/**
	 * Get's a tag array
	 * @return array
	 */
	public function getTagArray ( ) {
		$tags = array();
		if ( isset($this->Tags) ) {
			$tags = array();
			foreach ( $this->Tags as $Tag ) {
				$tags[] = $Tag->name;
			}
			sort($tags);
		}
		return $tags;
	}

	/**
	 * Sets the tagstr field
	 * @param int $value [optional]
	 * @return bool
	 */
	public function setTagstr ( $value = null ) {
		/// Default
		if ( is_null($value) ) {
			$tags = $this->getTagArray();
			$value = implode($tags, ', ');
		}
		// Is Change?
		if ( $this->tagstr != $value ) {
			$this->_set('tagstr', $value);
			return true;
		}
		// No Change
		return false;
	}

	/**
	 * Ensure Tagstr
	 * @return boolean	wheter or not to save
	 */
	public function ensureTagstr(){
		# Prepare
		$save = false;
		
		# Tagstr
		if ( $this->setTagstr() ) {
			$save = true;
		}
		
		# Done
		return $save;
	}
	
	/**
	 * Ensure Consistency
	 * @return boolean	wheter or not to save
	 */
	public function ensure(){
		$ensure = array(
			$this->ensureTagstr()
		);
		return in_array(true,$ensure);
	}
	
	/**
	 * preSave Event
	 * @return
	 */
	public function preSave ( $Event ) {
		# Prepare
		$Invoker = $Event->getInvoker();
		$result = true;
		
		# Ensure
		if ( self::ensure($Event) ) {
			// will save naturally
		}
		
		# Done
		return method_exists(get_parent_class($this),$parent_method = __FUNCTION__) ? parent::$parent_method($Event) : $result;
	}
	
	/**
	 * postSave Event
	 * @return
	 */
	public function postSave ( $Event ) {
		# Prepare
		$Invoker = $Event->getInvoker();
		$result = true;
		
		# Ensure
		if ( self::ensure($Event) ) {
			$this->save();
		}
		
		# Done
		return method_exists(get_parent_class($this),$parent_method = __FUNCTION__) ? parent::$parent_method($Event) : $result;
	}
	
}